# Generated by Django 4.1.4 on 2022-12-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forecast",
            name="temperature",
        ),
        migrations.AddField(
            model_name="forecast",
            name="max_temperature",
            field=models.CharField(default="max", max_length=4),
        ),
        migrations.AddField(
            model_name="forecast",
            name="min_temperature",
            field=models.CharField(default="min", max_length=4),
        ),
    ]
