# Generated by Django 4.1.4 on 2022-12-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "parser",
            "0002_remove_forecast_temperature_forecast_max_temperature_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="forecast",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
