# Generated by Django 4.1.4 on 2022-12-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0003_forecast_last_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecast",
            name="last_update",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
