# Generated by Django 4.1.4 on 2022-12-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0006_remove_forecast_max_temperature_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecast",
            name="last_update",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
