# Generated by Django 4.1.4 on 2022-12-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0007_alter_forecast_last_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecast",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
